// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef flballgame_h
#define flballgame_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
int main();
#endif
