// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef flexplorer_h
#define flexplorer_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *flbrow;
#include <FL/Fl_Input.H>
Fl_Double_Window* make_window();
int main();
#endif
