// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef flmath_h
#define flmath_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *userline;
#include <FL/Fl_Button.H>
extern Fl_Button *buttonnext;
#include <FL/Fl_Output.H>
extern Fl_Output *indicator;
Fl_Double_Window* make_window();
int main();
#endif
