// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "flmath.h"
#include "flmath.c"

Fl_Input *userline=(Fl_Input *)0;

Fl_Button *buttonnext=(Fl_Button *)0;

static void cb_buttonnext(Fl_Button*, void*) {
  printf( "Clear inputbox text \n" );

 indicator->value( valuemath() );
}

Fl_Output *indicator=(Fl_Output *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(360, 260, "KIDSMATH");
    w = o;
    { userline = new Fl_Input(30, 100, 285, 65);
    } // Fl_Input* userline
    { buttonnext = new Fl_Button(30, 185, 285, 30, "Next !!");
      buttonnext->callback((Fl_Callback*)cb_buttonnext);
    } // Fl_Button* buttonnext
    { indicator = new Fl_Output(30, 50, 285, 40);
      indicator->color((Fl_Color)221);
      indicator->textfont(1);
      indicator->textcolor((Fl_Color)97);
    } // Fl_Output* indicator
    o->end();
  } // Fl_Double_Window* o
  w->show();
  return w;
}

int main() {
  make_window();
  
  Fl::run();
  
  return 0;
}
